buildscript {
    dependencies {
        classpath "org.flywaydb:flyway-mysql:10.22.0"
        classpath "com.mysql:mysql-connector-j:9.3.0"
    }
}

plugins {
    id 'java'
    id 'groovy'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.jooq.jooq-codegen-gradle" version "3.19.18"
    id 'org.flywaydb.flyway' version '10.22.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

ext {
    lombokVersion = '1.18.36'
    groovyVersion = '4.0.24'
    vavrVersion = '1.0.1'
    jooqVersion = "3.19.18"
    mysqlConnectorVersion = '9.3.0'
    spockVersion = '2.4-M5-groovy-4.0'
    spockSubjectCollaboratorsVersion = '2.0.1'
    flywayVersion = '10.22.0'
}

java {
    sourceCompatibility = '21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    // groovy
    implementation "org.apache.groovy:groovy-all:${groovyVersion}"
    implementation "org.apache.groovy:groovy:${groovyVersion}"
    // lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    // vavr
    implementation "io.vavr:vavr:${vavrVersion}"
    // jooq
    implementation "org.jooq:jooq:${jooqVersion}"
    implementation "org.jooq:jooq-meta:${jooqVersion}"
    // flyway
    implementation "org.flywaydb:flyway-core:${flywayVersion}"
    implementation "org.flywaydb:flyway-mysql:${flywayVersion}"

    implementation "com.mysql:mysql-connector-j:${mysqlConnectorVersion}"

    jooqCodegen "com.mysql:mysql-connector-j:${mysqlConnectorVersion}"
    jooqCodegen "jakarta.xml.bind:jakarta.xml.bind-api:4.0.2"

    // テストスイートライブラリ
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.spockframework:spock-core:${spockVersion}"
    // Springのコントローラテストで必要
    testImplementation "org.spockframework:spock-spring:${spockVersion}"
    // Mocking
    testImplementation "cglib:cglib-nodep:3.3.0"
    // テスト用の軽量 DI
    testImplementation "com.blogspot.toomuchcoding:spock-subjects-collaborators-extension:${spockSubjectCollaboratorsVersion}"
    // Data Annotation使うときの警告を削除するときに必要
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
}


// Javaのコンパイル＆テストの設定
apply from: file('etc/gradle/java.gradle')

apply from: file('etc/gradle/jooq.gradle')

apply from: file('etc/gradle/flyway.gradle')
