services:
  mysql:
    image: mysql:latest
    container_name: mysql_florist
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "florist"
      MYSQL_USER: "florist"
      MYSQL_PASSWORD: "florist"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
