@startuml "florist"

package サービス層 {
  package 受注サービス {
    class 受注サービス {
      + 受注する(受注イベント)
    }
    interface 受注リポジトリ {
      + 受注する(受注集約)
    }
    class お届け日修正 {
      + お届け日を修正する(お届け日変更イベント)
    }
  }
  package 出荷サービス {
    class 出荷サービス {
      + 出荷する(出荷イベント)
    }
    interface 出荷リポジトリ {
      + 出荷する(出荷集約)
    }
  }
  package 発注サービス {
    class 発注サービス {
      + 発注する(発注イベント)
    }
    interface 発注リポジトリ {
      + 発注する
    }
  }
  package 入荷サービス {
    class 入荷サービス {
      + 入荷する(入荷イベント)
    }
    interface 入荷リポジトリ {
      + 入荷する
    }
  }
}

package ドメイン層 {
  package 花 {
    class 花束 {
      花束コード
      花リスト
    }

    class 花 {
      花コード
      花名称
      発注リードタイム
      品質維持可能日数
    }
  }

  package お客様 {
    class お客様 {
      お客様名
      お客様名メールアドレス
      クレジット番号
    }
  }

  package 受注 {

    class 注文イベント {
      ID
      贈り主氏名
      お届先住所
      お届け先氏名
      ご注文花束
      メッセージ要不要
      Option:お届けメッセージ
      お届けメッセージ先電話番号
    }

    class 受注イベント {
      ID
      贈り主氏名
      お届先住所
      お届け先氏名
      ご注文花束
      メッセージ要不要
      Option:お届けメッセージ
      お届けメッセージ先電話番号
    }

    class お届け日変更イベント {
      ID
      修正届け日
    }

    class 受注集約 {
      ID
      受注者名
      商品
      届け先
      届け日
      お届けメッセージ
      お届けメッセージ先電話番号
      + create(受注者名,商品,届け先,届け日,お届けメッセージ,お届け先電話番号)
      + Result<受注集約, 受注イベント> 受注する()
      + Result<受注集約, お届け日変更イベント> お届け日を変更する()
    }
  }

  package 出荷 {
    class 出荷イベント {
      受注者名
      商品
      届け先
      出荷日 
      お届けメッセージ
      お届けメッセージ先電話番号
    }

    class 出荷集約 {
      受注者名
      商品
      届け先
      出荷日
      お届けメッセージ
      お届けメッセージ先電話番号
      + create(受注者名,商品,届け先,出荷日,お届けメッセージ,お届け先電話番号)
      + Result<受注集約, 出荷イベント> 出荷する()
    }
  }

  package 発注 {
    class 発注イベント {
      ID
      花リスト
      購入単位セット数
    }
  }

  package 入荷 {
    class 入荷イベント {
      ID
      花リスト
      購入単位セット数
    }
  }
}

花 "1..*" ..l> "1" 花束
受注イベント ..d> 花束

お届け日変更イベント "1" ..u> "1" 受注イベント
お客様 "1" ..u> "0..*" 受注イベント
受注イベント ..r> 出荷イベント
受注イベント .. 受注集約
出荷イベント .. 出荷集約
発注イベント "1" ..> "0..*" 花
入荷イベント "1" ..> "0..*" 花

受注サービス ..d> 受注イベント
受注サービス ..r 受注リポジトリ
受注リポジトリ ..d> 受注集約
出荷サービス ..d> 出荷イベント
出荷サービス ..r 出荷リポジトリ
出荷リポジトリ ..d> 出荷集約
発注サービス ..d> 発注イベント
発注サービス ..r 発注リポジトリ
入荷サービス ..d> 入荷イベント
入荷サービス ..r 入荷リポジトリ
@enduml